version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - testes-elastic
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    networks:
      - testes-elastic
    depends_on:
      - elasticsearch
networks: 
  testes-elastic:
    driver: bridge